### ISSUE TITLE
Did you figure out how to send "Mow Zone A" or "Mow Subzone1" command?

### ISSUE THREAD

**Issue by frankhommers** [arjanmels/RoboMowRC#1]
Did you figure out how to send "Mow Zone A" or "Mow Subzone1" command?

I'd like to know ;-)

**Comment by frankhommers** [comment]
Figured it out myself! ;-)

**Comment by rcojoe** [comment]
@frankhommers Frank, could you share what you found?

**Comment by frankhommers** [comment]
I did it this way: https://github.com/drbytes/RobomowRemoteControl/issues/5#issuecomment-623395745
